/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedKanbanIndexRouteImport } from './routes/_authenticated/kanban/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedEcommerceIndexRouteImport } from './routes/_authenticated/ecommerce/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedEcommerceTrafficIndexRouteImport } from './routes/_authenticated/ecommerce/traffic/index'
import { Route as AuthenticatedEcommerceInventoryIndexRouteImport } from './routes/_authenticated/ecommerce/inventory/index'
import { Route as AuthenticatedEcommerceAftersalesIndexRouteImport } from './routes/_authenticated/ecommerce/aftersales/index'
import { Route as AuthenticatedEcommerceAdsIndexRouteImport } from './routes/_authenticated/ecommerce/ads/index'
import { Route as AuthenticatedEcommerceSettingsStoresIndexRouteImport } from './routes/_authenticated/ecommerce/settings/stores/index'
import { Route as AuthenticatedEcommerceSettingsDataIndexRouteImport } from './routes/_authenticated/ecommerce/settings/data/index'
import { Route as AuthenticatedEcommerceSettingsChannelsIndexRouteImport } from './routes/_authenticated/ecommerce/settings/channels/index'
import { Route as AuthenticatedEcommerceSalesTrendIndexRouteImport } from './routes/_authenticated/ecommerce/sales/trend/index'
import { Route as AuthenticatedEcommerceSalesOrdersIndexRouteImport } from './routes/_authenticated/ecommerce/sales/orders/index'
import { Route as AuthenticatedEcommerceSalesChannelIndexRouteImport } from './routes/_authenticated/ecommerce/sales/channel/index'
import { Route as AuthenticatedEcommerceProductsListIndexRouteImport } from './routes/_authenticated/ecommerce/products/list/index'
import { Route as AuthenticatedEcommerceProductsHotIndexRouteImport } from './routes/_authenticated/ecommerce/products/hot/index'
import { Route as AuthenticatedEcommerceProductsCategoryIndexRouteImport } from './routes/_authenticated/ecommerce/products/category/index'
import { Route as AuthenticatedEcommerceInventoryAlertsIndexRouteImport } from './routes/_authenticated/ecommerce/inventory/alerts/index'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedKanbanIndexRoute =
  AuthenticatedKanbanIndexRouteImport.update({
    id: '/kanban/',
    path: '/kanban/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcommerceIndexRoute =
  AuthenticatedEcommerceIndexRouteImport.update({
    id: '/ecommerce/',
    path: '/ecommerce/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcommerceTrafficIndexRoute =
  AuthenticatedEcommerceTrafficIndexRouteImport.update({
    id: '/ecommerce/traffic/',
    path: '/ecommerce/traffic/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcommerceInventoryIndexRoute =
  AuthenticatedEcommerceInventoryIndexRouteImport.update({
    id: '/ecommerce/inventory/',
    path: '/ecommerce/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcommerceAftersalesIndexRoute =
  AuthenticatedEcommerceAftersalesIndexRouteImport.update({
    id: '/ecommerce/aftersales/',
    path: '/ecommerce/aftersales/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcommerceAdsIndexRoute =
  AuthenticatedEcommerceAdsIndexRouteImport.update({
    id: '/ecommerce/ads/',
    path: '/ecommerce/ads/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcommerceSettingsStoresIndexRoute =
  AuthenticatedEcommerceSettingsStoresIndexRouteImport.update({
    id: '/ecommerce/settings/stores/',
    path: '/ecommerce/settings/stores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcommerceSettingsDataIndexRoute =
  AuthenticatedEcommerceSettingsDataIndexRouteImport.update({
    id: '/ecommerce/settings/data/',
    path: '/ecommerce/settings/data/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcommerceSettingsChannelsIndexRoute =
  AuthenticatedEcommerceSettingsChannelsIndexRouteImport.update({
    id: '/ecommerce/settings/channels/',
    path: '/ecommerce/settings/channels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcommerceSalesTrendIndexRoute =
  AuthenticatedEcommerceSalesTrendIndexRouteImport.update({
    id: '/ecommerce/sales/trend/',
    path: '/ecommerce/sales/trend/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcommerceSalesOrdersIndexRoute =
  AuthenticatedEcommerceSalesOrdersIndexRouteImport.update({
    id: '/ecommerce/sales/orders/',
    path: '/ecommerce/sales/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcommerceSalesChannelIndexRoute =
  AuthenticatedEcommerceSalesChannelIndexRouteImport.update({
    id: '/ecommerce/sales/channel/',
    path: '/ecommerce/sales/channel/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcommerceProductsListIndexRoute =
  AuthenticatedEcommerceProductsListIndexRouteImport.update({
    id: '/ecommerce/products/list/',
    path: '/ecommerce/products/list/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcommerceProductsHotIndexRoute =
  AuthenticatedEcommerceProductsHotIndexRouteImport.update({
    id: '/ecommerce/products/hot/',
    path: '/ecommerce/products/hot/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcommerceProductsCategoryIndexRoute =
  AuthenticatedEcommerceProductsCategoryIndexRouteImport.update({
    id: '/ecommerce/products/category/',
    path: '/ecommerce/products/category/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEcommerceInventoryAlertsIndexRoute =
  AuthenticatedEcommerceInventoryAlertsIndexRouteImport.update({
    id: '/ecommerce/inventory/alerts/',
    path: '/ecommerce/inventory/alerts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/ecommerce/': typeof AuthenticatedEcommerceIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/kanban/': typeof AuthenticatedKanbanIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/ecommerce/ads/': typeof AuthenticatedEcommerceAdsIndexRoute
  '/ecommerce/aftersales/': typeof AuthenticatedEcommerceAftersalesIndexRoute
  '/ecommerce/inventory/': typeof AuthenticatedEcommerceInventoryIndexRoute
  '/ecommerce/traffic/': typeof AuthenticatedEcommerceTrafficIndexRoute
  '/ecommerce/inventory/alerts/': typeof AuthenticatedEcommerceInventoryAlertsIndexRoute
  '/ecommerce/products/category/': typeof AuthenticatedEcommerceProductsCategoryIndexRoute
  '/ecommerce/products/hot/': typeof AuthenticatedEcommerceProductsHotIndexRoute
  '/ecommerce/products/list/': typeof AuthenticatedEcommerceProductsListIndexRoute
  '/ecommerce/sales/channel/': typeof AuthenticatedEcommerceSalesChannelIndexRoute
  '/ecommerce/sales/orders/': typeof AuthenticatedEcommerceSalesOrdersIndexRoute
  '/ecommerce/sales/trend/': typeof AuthenticatedEcommerceSalesTrendIndexRoute
  '/ecommerce/settings/channels/': typeof AuthenticatedEcommerceSettingsChannelsIndexRoute
  '/ecommerce/settings/data/': typeof AuthenticatedEcommerceSettingsDataIndexRoute
  '/ecommerce/settings/stores/': typeof AuthenticatedEcommerceSettingsStoresIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/ecommerce': typeof AuthenticatedEcommerceIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/kanban': typeof AuthenticatedKanbanIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/ecommerce/ads': typeof AuthenticatedEcommerceAdsIndexRoute
  '/ecommerce/aftersales': typeof AuthenticatedEcommerceAftersalesIndexRoute
  '/ecommerce/inventory': typeof AuthenticatedEcommerceInventoryIndexRoute
  '/ecommerce/traffic': typeof AuthenticatedEcommerceTrafficIndexRoute
  '/ecommerce/inventory/alerts': typeof AuthenticatedEcommerceInventoryAlertsIndexRoute
  '/ecommerce/products/category': typeof AuthenticatedEcommerceProductsCategoryIndexRoute
  '/ecommerce/products/hot': typeof AuthenticatedEcommerceProductsHotIndexRoute
  '/ecommerce/products/list': typeof AuthenticatedEcommerceProductsListIndexRoute
  '/ecommerce/sales/channel': typeof AuthenticatedEcommerceSalesChannelIndexRoute
  '/ecommerce/sales/orders': typeof AuthenticatedEcommerceSalesOrdersIndexRoute
  '/ecommerce/sales/trend': typeof AuthenticatedEcommerceSalesTrendIndexRoute
  '/ecommerce/settings/channels': typeof AuthenticatedEcommerceSettingsChannelsIndexRoute
  '/ecommerce/settings/data': typeof AuthenticatedEcommerceSettingsDataIndexRoute
  '/ecommerce/settings/stores': typeof AuthenticatedEcommerceSettingsStoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/ecommerce/': typeof AuthenticatedEcommerceIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/kanban/': typeof AuthenticatedKanbanIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/ecommerce/ads/': typeof AuthenticatedEcommerceAdsIndexRoute
  '/_authenticated/ecommerce/aftersales/': typeof AuthenticatedEcommerceAftersalesIndexRoute
  '/_authenticated/ecommerce/inventory/': typeof AuthenticatedEcommerceInventoryIndexRoute
  '/_authenticated/ecommerce/traffic/': typeof AuthenticatedEcommerceTrafficIndexRoute
  '/_authenticated/ecommerce/inventory/alerts/': typeof AuthenticatedEcommerceInventoryAlertsIndexRoute
  '/_authenticated/ecommerce/products/category/': typeof AuthenticatedEcommerceProductsCategoryIndexRoute
  '/_authenticated/ecommerce/products/hot/': typeof AuthenticatedEcommerceProductsHotIndexRoute
  '/_authenticated/ecommerce/products/list/': typeof AuthenticatedEcommerceProductsListIndexRoute
  '/_authenticated/ecommerce/sales/channel/': typeof AuthenticatedEcommerceSalesChannelIndexRoute
  '/_authenticated/ecommerce/sales/orders/': typeof AuthenticatedEcommerceSalesOrdersIndexRoute
  '/_authenticated/ecommerce/sales/trend/': typeof AuthenticatedEcommerceSalesTrendIndexRoute
  '/_authenticated/ecommerce/settings/channels/': typeof AuthenticatedEcommerceSettingsChannelsIndexRoute
  '/_authenticated/ecommerce/settings/data/': typeof AuthenticatedEcommerceSettingsDataIndexRoute
  '/_authenticated/ecommerce/settings/stores/': typeof AuthenticatedEcommerceSettingsStoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps/'
    | '/chats/'
    | '/ecommerce/'
    | '/help-center/'
    | '/kanban/'
    | '/settings/'
    | '/tasks/'
    | '/users/'
    | '/ecommerce/ads/'
    | '/ecommerce/aftersales/'
    | '/ecommerce/inventory/'
    | '/ecommerce/traffic/'
    | '/ecommerce/inventory/alerts/'
    | '/ecommerce/products/category/'
    | '/ecommerce/products/hot/'
    | '/ecommerce/products/list/'
    | '/ecommerce/sales/channel/'
    | '/ecommerce/sales/orders/'
    | '/ecommerce/sales/trend/'
    | '/ecommerce/settings/channels/'
    | '/ecommerce/settings/data/'
    | '/ecommerce/settings/stores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/ecommerce'
    | '/help-center'
    | '/kanban'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/ecommerce/ads'
    | '/ecommerce/aftersales'
    | '/ecommerce/inventory'
    | '/ecommerce/traffic'
    | '/ecommerce/inventory/alerts'
    | '/ecommerce/products/category'
    | '/ecommerce/products/hot'
    | '/ecommerce/products/list'
    | '/ecommerce/sales/channel'
    | '/ecommerce/sales/orders'
    | '/ecommerce/sales/trend'
    | '/ecommerce/settings/channels'
    | '/ecommerce/settings/data'
    | '/ecommerce/settings/stores'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/ecommerce/'
    | '/_authenticated/help-center/'
    | '/_authenticated/kanban/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/ecommerce/ads/'
    | '/_authenticated/ecommerce/aftersales/'
    | '/_authenticated/ecommerce/inventory/'
    | '/_authenticated/ecommerce/traffic/'
    | '/_authenticated/ecommerce/inventory/alerts/'
    | '/_authenticated/ecommerce/products/category/'
    | '/_authenticated/ecommerce/products/hot/'
    | '/_authenticated/ecommerce/products/list/'
    | '/_authenticated/ecommerce/sales/channel/'
    | '/_authenticated/ecommerce/sales/orders/'
    | '/_authenticated/ecommerce/sales/trend/'
    | '/_authenticated/ecommerce/settings/channels/'
    | '/_authenticated/ecommerce/settings/data/'
    | '/_authenticated/ecommerce/settings/stores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/kanban/': {
      id: '/_authenticated/kanban/'
      path: '/kanban'
      fullPath: '/kanban/'
      preLoaderRoute: typeof AuthenticatedKanbanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecommerce/': {
      id: '/_authenticated/ecommerce/'
      path: '/ecommerce'
      fullPath: '/ecommerce/'
      preLoaderRoute: typeof AuthenticatedEcommerceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecommerce/traffic/': {
      id: '/_authenticated/ecommerce/traffic/'
      path: '/ecommerce/traffic'
      fullPath: '/ecommerce/traffic/'
      preLoaderRoute: typeof AuthenticatedEcommerceTrafficIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecommerce/inventory/': {
      id: '/_authenticated/ecommerce/inventory/'
      path: '/ecommerce/inventory'
      fullPath: '/ecommerce/inventory/'
      preLoaderRoute: typeof AuthenticatedEcommerceInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecommerce/aftersales/': {
      id: '/_authenticated/ecommerce/aftersales/'
      path: '/ecommerce/aftersales'
      fullPath: '/ecommerce/aftersales/'
      preLoaderRoute: typeof AuthenticatedEcommerceAftersalesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecommerce/ads/': {
      id: '/_authenticated/ecommerce/ads/'
      path: '/ecommerce/ads'
      fullPath: '/ecommerce/ads/'
      preLoaderRoute: typeof AuthenticatedEcommerceAdsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecommerce/settings/stores/': {
      id: '/_authenticated/ecommerce/settings/stores/'
      path: '/ecommerce/settings/stores'
      fullPath: '/ecommerce/settings/stores/'
      preLoaderRoute: typeof AuthenticatedEcommerceSettingsStoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecommerce/settings/data/': {
      id: '/_authenticated/ecommerce/settings/data/'
      path: '/ecommerce/settings/data'
      fullPath: '/ecommerce/settings/data/'
      preLoaderRoute: typeof AuthenticatedEcommerceSettingsDataIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecommerce/settings/channels/': {
      id: '/_authenticated/ecommerce/settings/channels/'
      path: '/ecommerce/settings/channels'
      fullPath: '/ecommerce/settings/channels/'
      preLoaderRoute: typeof AuthenticatedEcommerceSettingsChannelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecommerce/sales/trend/': {
      id: '/_authenticated/ecommerce/sales/trend/'
      path: '/ecommerce/sales/trend'
      fullPath: '/ecommerce/sales/trend/'
      preLoaderRoute: typeof AuthenticatedEcommerceSalesTrendIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecommerce/sales/orders/': {
      id: '/_authenticated/ecommerce/sales/orders/'
      path: '/ecommerce/sales/orders'
      fullPath: '/ecommerce/sales/orders/'
      preLoaderRoute: typeof AuthenticatedEcommerceSalesOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecommerce/sales/channel/': {
      id: '/_authenticated/ecommerce/sales/channel/'
      path: '/ecommerce/sales/channel'
      fullPath: '/ecommerce/sales/channel/'
      preLoaderRoute: typeof AuthenticatedEcommerceSalesChannelIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecommerce/products/list/': {
      id: '/_authenticated/ecommerce/products/list/'
      path: '/ecommerce/products/list'
      fullPath: '/ecommerce/products/list/'
      preLoaderRoute: typeof AuthenticatedEcommerceProductsListIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecommerce/products/hot/': {
      id: '/_authenticated/ecommerce/products/hot/'
      path: '/ecommerce/products/hot'
      fullPath: '/ecommerce/products/hot/'
      preLoaderRoute: typeof AuthenticatedEcommerceProductsHotIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecommerce/products/category/': {
      id: '/_authenticated/ecommerce/products/category/'
      path: '/ecommerce/products/category'
      fullPath: '/ecommerce/products/category/'
      preLoaderRoute: typeof AuthenticatedEcommerceProductsCategoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecommerce/inventory/alerts/': {
      id: '/_authenticated/ecommerce/inventory/alerts/'
      path: '/ecommerce/inventory/alerts'
      fullPath: '/ecommerce/inventory/alerts/'
      preLoaderRoute: typeof AuthenticatedEcommerceInventoryAlertsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedEcommerceIndexRoute: typeof AuthenticatedEcommerceIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedKanbanIndexRoute: typeof AuthenticatedKanbanIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedEcommerceAdsIndexRoute: typeof AuthenticatedEcommerceAdsIndexRoute
  AuthenticatedEcommerceAftersalesIndexRoute: typeof AuthenticatedEcommerceAftersalesIndexRoute
  AuthenticatedEcommerceInventoryIndexRoute: typeof AuthenticatedEcommerceInventoryIndexRoute
  AuthenticatedEcommerceTrafficIndexRoute: typeof AuthenticatedEcommerceTrafficIndexRoute
  AuthenticatedEcommerceInventoryAlertsIndexRoute: typeof AuthenticatedEcommerceInventoryAlertsIndexRoute
  AuthenticatedEcommerceProductsCategoryIndexRoute: typeof AuthenticatedEcommerceProductsCategoryIndexRoute
  AuthenticatedEcommerceProductsHotIndexRoute: typeof AuthenticatedEcommerceProductsHotIndexRoute
  AuthenticatedEcommerceProductsListIndexRoute: typeof AuthenticatedEcommerceProductsListIndexRoute
  AuthenticatedEcommerceSalesChannelIndexRoute: typeof AuthenticatedEcommerceSalesChannelIndexRoute
  AuthenticatedEcommerceSalesOrdersIndexRoute: typeof AuthenticatedEcommerceSalesOrdersIndexRoute
  AuthenticatedEcommerceSalesTrendIndexRoute: typeof AuthenticatedEcommerceSalesTrendIndexRoute
  AuthenticatedEcommerceSettingsChannelsIndexRoute: typeof AuthenticatedEcommerceSettingsChannelsIndexRoute
  AuthenticatedEcommerceSettingsDataIndexRoute: typeof AuthenticatedEcommerceSettingsDataIndexRoute
  AuthenticatedEcommerceSettingsStoresIndexRoute: typeof AuthenticatedEcommerceSettingsStoresIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedEcommerceIndexRoute: AuthenticatedEcommerceIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedKanbanIndexRoute: AuthenticatedKanbanIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedEcommerceAdsIndexRoute: AuthenticatedEcommerceAdsIndexRoute,
  AuthenticatedEcommerceAftersalesIndexRoute:
    AuthenticatedEcommerceAftersalesIndexRoute,
  AuthenticatedEcommerceInventoryIndexRoute:
    AuthenticatedEcommerceInventoryIndexRoute,
  AuthenticatedEcommerceTrafficIndexRoute:
    AuthenticatedEcommerceTrafficIndexRoute,
  AuthenticatedEcommerceInventoryAlertsIndexRoute:
    AuthenticatedEcommerceInventoryAlertsIndexRoute,
  AuthenticatedEcommerceProductsCategoryIndexRoute:
    AuthenticatedEcommerceProductsCategoryIndexRoute,
  AuthenticatedEcommerceProductsHotIndexRoute:
    AuthenticatedEcommerceProductsHotIndexRoute,
  AuthenticatedEcommerceProductsListIndexRoute:
    AuthenticatedEcommerceProductsListIndexRoute,
  AuthenticatedEcommerceSalesChannelIndexRoute:
    AuthenticatedEcommerceSalesChannelIndexRoute,
  AuthenticatedEcommerceSalesOrdersIndexRoute:
    AuthenticatedEcommerceSalesOrdersIndexRoute,
  AuthenticatedEcommerceSalesTrendIndexRoute:
    AuthenticatedEcommerceSalesTrendIndexRoute,
  AuthenticatedEcommerceSettingsChannelsIndexRoute:
    AuthenticatedEcommerceSettingsChannelsIndexRoute,
  AuthenticatedEcommerceSettingsDataIndexRoute:
    AuthenticatedEcommerceSettingsDataIndexRoute,
  AuthenticatedEcommerceSettingsStoresIndexRoute:
    AuthenticatedEcommerceSettingsStoresIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
